name: CI

on: 
  push:
    branches: 
      - release/*

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build GHost Theame
      run: |
        npm install
        npm run zip
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/beitostolen-live.zip
        asset_name: BeitostolenLiveGhostTheame
        tag: ${{ github.ref }}
        overwrite: true
